repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key
-   repo: local
    hooks:
    -   id: pytest
        name: run tests
        entry: make test
        pass_filenames: false
        language: system
        types: [ python ]
-   repo: local
    hooks:
    -   id: lint
        name: linting & formatting
        entry: make test
        pass_filenames: false
        language: system
        types: [ python ]
