[tool.poetry]
name = "{{cookiecutter.project_name}}"
version = "{{cookiecutter.version}}"
description = "{{cookiecutter.project_short_description}}"
authors = ["{{cookiecutter.full_name}} <{{cookiecutter.email}}>"]
license = "{{cookiecutter.license}}"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^7.2.0"
mypy = "*"
black = "*"
flake8 = "*"
bandit = "*"
coverage = "*"
{% if cookiecutter.cli_builder == 'y' %}typer = {extras = ["all"], version = "^0.7.0"}{% endif %}

[tool.poetry.groups.dev]
optional = true

[tool.poetry.groups.dev.dependencies]
# placeholder for dev env dependencies
